import "@/styles/globals.css";
import { ThemeProvider } from "@/components/theme-provider"

import { type Metadata } from "next";
import { Roboto_Mono } from "next/font/google";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${robotoMono.variable}`} suppressHydrationWarning>
      <body>
                  <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
                      {children}
            </ThemeProvider>
</body>
    </html>
  );
}
