import "@/styles/globals.css";
import { ThemeProvider } from "@/components/theme-provider"

import { type Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import { Navbar } from "@/components/Navbar";
import { auth } from "@/server/auth";

// 
export const metadata: Metadata = {
  title: "StoryQuest",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
const session = await auth()

  return (
    <html lang="en" className={`${robotoMono.variable}`} suppressHydrationWarning>
      <body className="min-h-screen h-screen w-screen flex flex-col bg-background text-foreground antialiased">
                  <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >

            {session && (
              <Navbar
              user={{ name: session?.user?.name, email: session?.user?.email, image: session?.user?.image }}
              />
            )}
        {children}
            </ThemeProvider>
</body>
    </html>
  );
}
